apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
    include.release.openshift.io/ibm-cloud-managed-: ""
    include.release.openshift.io/self-managed-high-availability-: ""
    include.release.openshift.io/single-node-developer-: ""
  name: cloudprivateipconfigs.cloud.network.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          metadata:
            properties:
              name:
                anyOf:
                - format: ipv4
                - pattern: ^[0-9a-f]{4}(\.[0-9a-f]{4}){7}$
                type: string
