apiVersion: apiextensions.k8s.io/v1 # Hack because controller-gen complains if we don't have this
name: "[Custom] NotStableConfigType"
crd: 0000_50_my-operator_01_notstableconfigtypes-CustomNoUpgrade.crd.yaml
tests:
  onCreate:
  - name: Should be able to create a minimal NotStableConfigType
    initial: |
      apiVersion: example.openshift.io/v1alpha1
      kind: NotStableConfigType
      spec:
        newField: foo
    expected: |
      apiVersion: example.openshift.io/v1alpha1
      kind: NotStableConfigType
      spec:
        newField: foo
