apiVersion: apiextensions.k8s.io/v1 # Hack because controller-gen complains if we don't have this
name: "[TechPreviewNoUpgrade] Example API"
crd: 0000_50_my-operator_01_stableconfigtypes-TechPreviewNoUpgrade.crd.yaml
tests:
  onCreate:
  - name: Should persist stable fields
    initial: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        stableField: "Allowed"
        immutableField: foo
    expected: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        stableField: "Allowed"
        immutableField: foo
  - name: Should persist a tech preview field
    initial: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        coolNewField: "Invalid"
        immutableField: foo
    expected: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        coolNewField: "Invalid"
        immutableField: foo
  - name: With an EvolvingUnion, Should allow an empty enum value
    initial: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        evolvingUnion:
          type: ""
        immutableField: foo
    expected: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        evolvingUnion:
          type: ""
        immutableField: foo
  - name: With an EvolvingUnion, Should allow a Stable enum value
    initial: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        evolvingUnion:
          type: StableValue
        immutableField: foo
    expected: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        evolvingUnion:
          type: StableValue
        immutableField: foo
  - name: With an EvolvingUnion, Should allow a TechPreview enum value
    initial: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        evolvingUnion:
          type: TechPreviewOnlyValue
        immutableField: foo
    expected: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        evolvingUnion:
          type: TechPreviewOnlyValue
        immutableField: foo
  onUpdate:
  - name: Should not allow removal of a tech preview field
    initial: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        coolNewField: "Invalid"
        immutableField: foo
    updated: |
      apiVersion: example.openshift.io/v1
      kind: StableConfigType
      spec:
        immutableField: foo
    expectedError: "spec: Invalid value: \"object\": coolNewField may not be removed once set"
