apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    feature-gate.release.openshift.io/PlatformOperators: "true"
  name: platformoperators.platform.openshift.io
